// Code generated by protoc-gen-go. DO NOT EDIT.
// source: image_info.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//for uploading image
type UploadImageRequest struct {
	// Types that are valid to be assigned to Data:
	//	*UploadImageRequest_Info
	//	*UploadImageRequest_Chunkdata
	Data                 isUploadImageRequest_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *UploadImageRequest) Reset()         { *m = UploadImageRequest{} }
func (m *UploadImageRequest) String() string { return proto.CompactTextString(m) }
func (*UploadImageRequest) ProtoMessage()    {}
func (*UploadImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8085f4b4731c381e, []int{0}
}

func (m *UploadImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadImageRequest.Unmarshal(m, b)
}
func (m *UploadImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadImageRequest.Marshal(b, m, deterministic)
}
func (m *UploadImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadImageRequest.Merge(m, src)
}
func (m *UploadImageRequest) XXX_Size() int {
	return xxx_messageInfo_UploadImageRequest.Size(m)
}
func (m *UploadImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadImageRequest proto.InternalMessageInfo

type isUploadImageRequest_Data interface {
	isUploadImageRequest_Data()
}

type UploadImageRequest_Info struct {
	Info *ImageInfo `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type UploadImageRequest_Chunkdata struct {
	Chunkdata []byte `protobuf:"bytes,2,opt,name=chunkdata,proto3,oneof"`
}

func (*UploadImageRequest_Info) isUploadImageRequest_Data() {}

func (*UploadImageRequest_Chunkdata) isUploadImageRequest_Data() {}

func (m *UploadImageRequest) GetData() isUploadImageRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UploadImageRequest) GetInfo() *ImageInfo {
	if x, ok := m.GetData().(*UploadImageRequest_Info); ok {
		return x.Info
	}
	return nil
}

func (m *UploadImageRequest) GetChunkdata() []byte {
	if x, ok := m.GetData().(*UploadImageRequest_Chunkdata); ok {
		return x.Chunkdata
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*UploadImageRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*UploadImageRequest_Info)(nil),
		(*UploadImageRequest_Chunkdata)(nil),
	}
}

type ImageInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ImageType            string   `protobuf:"bytes,2,opt,name=image_type,json=imageType,proto3" json:"image_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageInfo) Reset()         { *m = ImageInfo{} }
func (m *ImageInfo) String() string { return proto.CompactTextString(m) }
func (*ImageInfo) ProtoMessage()    {}
func (*ImageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8085f4b4731c381e, []int{1}
}

func (m *ImageInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageInfo.Unmarshal(m, b)
}
func (m *ImageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageInfo.Marshal(b, m, deterministic)
}
func (m *ImageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageInfo.Merge(m, src)
}
func (m *ImageInfo) XXX_Size() int {
	return xxx_messageInfo_ImageInfo.Size(m)
}
func (m *ImageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ImageInfo proto.InternalMessageInfo

func (m *ImageInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ImageInfo) GetImageType() string {
	if m != nil {
		return m.ImageType
	}
	return ""
}

type UploadImageResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size                 uint32   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadImageResponse) Reset()         { *m = UploadImageResponse{} }
func (m *UploadImageResponse) String() string { return proto.CompactTextString(m) }
func (*UploadImageResponse) ProtoMessage()    {}
func (*UploadImageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8085f4b4731c381e, []int{2}
}

func (m *UploadImageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadImageResponse.Unmarshal(m, b)
}
func (m *UploadImageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadImageResponse.Marshal(b, m, deterministic)
}
func (m *UploadImageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadImageResponse.Merge(m, src)
}
func (m *UploadImageResponse) XXX_Size() int {
	return xxx_messageInfo_UploadImageResponse.Size(m)
}
func (m *UploadImageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadImageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadImageResponse proto.InternalMessageInfo

func (m *UploadImageResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UploadImageResponse) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func init() {
	proto.RegisterType((*UploadImageRequest)(nil), "proto.UploadImageRequest")
	proto.RegisterType((*ImageInfo)(nil), "proto.ImageInfo")
	proto.RegisterType((*UploadImageResponse)(nil), "proto.UploadImageResponse")
}

func init() { proto.RegisterFile("image_info.proto", fileDescriptor_8085f4b4731c381e) }

var fileDescriptor_8085f4b4731c381e = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x13, 0x89, 0x85, 0x9d, 0x2a, 0x94, 0xf1, 0x52, 0x03, 0x96, 0x92, 0x83, 0xe4, 0xd4,
	0x42, 0x3d, 0xeb, 0xc1, 0x53, 0x7a, 0x5d, 0xf5, 0xaa, 0x6c, 0x9b, 0x49, 0x0c, 0xb6, 0xbb, 0x6b,
	0x76, 0xa3, 0xd4, 0x4f, 0x2f, 0x99, 0x15, 0xff, 0x60, 0x4e, 0x33, 0x3b, 0xef, 0xcd, 0x8f, 0x79,
	0x0b, 0x93, 0x66, 0xaf, 0x6a, 0x7a, 0x6a, 0x74, 0x65, 0x16, 0xb6, 0x35, 0xde, 0xe0, 0x31, 0x97,
	0x74, 0x56, 0x1b, 0x53, 0xef, 0x68, 0xc9, 0xaf, 0x4d, 0x57, 0x2d, 0xdf, 0x5b, 0x65, 0x2d, 0xb5,
	0x2e, 0xd8, 0xb2, 0x12, 0xf0, 0xc1, 0xee, 0x8c, 0x2a, 0xd7, 0x3d, 0x40, 0xd2, 0x6b, 0x47, 0xce,
	0xe3, 0x25, 0x24, 0x3d, 0x6a, 0x1a, 0xcf, 0xe3, 0x7c, 0xbc, 0x9a, 0x04, 0xef, 0x82, 0x2d, 0x6b,
	0x5d, 0x99, 0x22, 0x92, 0xac, 0xe3, 0x0c, 0xc4, 0xf6, 0xb9, 0xd3, 0x2f, 0xa5, 0xf2, 0x6a, 0x7a,
	0x34, 0x8f, 0xf3, 0x93, 0x22, 0x92, 0x3f, 0xa3, 0xdb, 0x11, 0x24, 0x7d, 0xcd, 0x6e, 0x40, 0x7c,
	0x2f, 0x23, 0x42, 0xa2, 0xd5, 0x9e, 0x18, 0x2e, 0x24, 0xf7, 0x78, 0x01, 0x10, 0x12, 0xf8, 0x83,
	0x25, 0x26, 0x09, 0x29, 0x78, 0x72, 0x7f, 0xb0, 0x94, 0x5d, 0xc3, 0xd9, 0x9f, 0x2b, 0x9d, 0x35,
	0xda, 0xd1, 0x20, 0x09, 0x21, 0x71, 0xcd, 0x47, 0x60, 0x9c, 0x4a, 0xee, 0x57, 0x8f, 0x80, 0xbc,
	0x18, 0x18, 0x77, 0xd4, 0xbe, 0x35, 0x5b, 0xc2, 0x02, 0xc6, 0xbf, 0xa0, 0x78, 0xfe, 0x95, 0xf2,
	0xff, 0x77, 0xa4, 0xe9, 0x90, 0x14, 0x6e, 0xc8, 0xa2, 0x3c, 0xde, 0x8c, 0x58, 0xbe, 0xfa, 0x0c,
	0x00, 0x00, 0xff, 0xff, 0xa1, 0xa5, 0xb2, 0xf3, 0x86, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ImageUploadServiceClient is the client API for ImageUploadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ImageUploadServiceClient interface {
	UploadImage(ctx context.Context, opts ...grpc.CallOption) (ImageUploadService_UploadImageClient, error)
}

type imageUploadServiceClient struct {
	cc *grpc.ClientConn
}

func NewImageUploadServiceClient(cc *grpc.ClientConn) ImageUploadServiceClient {
	return &imageUploadServiceClient{cc}
}

func (c *imageUploadServiceClient) UploadImage(ctx context.Context, opts ...grpc.CallOption) (ImageUploadService_UploadImageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ImageUploadService_serviceDesc.Streams[0], "/proto.ImageUploadService/UploadImage", opts...)
	if err != nil {
		return nil, err
	}
	x := &imageUploadServiceUploadImageClient{stream}
	return x, nil
}

type ImageUploadService_UploadImageClient interface {
	Send(*UploadImageRequest) error
	CloseAndRecv() (*UploadImageResponse, error)
	grpc.ClientStream
}

type imageUploadServiceUploadImageClient struct {
	grpc.ClientStream
}

func (x *imageUploadServiceUploadImageClient) Send(m *UploadImageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *imageUploadServiceUploadImageClient) CloseAndRecv() (*UploadImageResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadImageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ImageUploadServiceServer is the server API for ImageUploadService service.
type ImageUploadServiceServer interface {
	UploadImage(ImageUploadService_UploadImageServer) error
}

// UnimplementedImageUploadServiceServer can be embedded to have forward compatible implementations.
type UnimplementedImageUploadServiceServer struct {
}

func (*UnimplementedImageUploadServiceServer) UploadImage(srv ImageUploadService_UploadImageServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadImage not implemented")
}

func RegisterImageUploadServiceServer(s *grpc.Server, srv ImageUploadServiceServer) {
	s.RegisterService(&_ImageUploadService_serviceDesc, srv)
}

func _ImageUploadService_UploadImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ImageUploadServiceServer).UploadImage(&imageUploadServiceUploadImageServer{stream})
}

type ImageUploadService_UploadImageServer interface {
	SendAndClose(*UploadImageResponse) error
	Recv() (*UploadImageRequest, error)
	grpc.ServerStream
}

type imageUploadServiceUploadImageServer struct {
	grpc.ServerStream
}

func (x *imageUploadServiceUploadImageServer) SendAndClose(m *UploadImageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *imageUploadServiceUploadImageServer) Recv() (*UploadImageRequest, error) {
	m := new(UploadImageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ImageUploadService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ImageUploadService",
	HandlerType: (*ImageUploadServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadImage",
			Handler:       _ImageUploadService_UploadImage_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "image_info.proto",
}
